FROM ubuntu:18.04 AS compiled

RUN apt-get update \
    && apt-get -y install g++ g++-multilib make cmake automake autoconf bison flex time libtool libbdd-dev gdb valgrind

#####################

FROM compiled AS final

WORKDIR /app

CMD ./build

#ENV dir ../data/ppddl/ippc2006
#ENV inst elevators

#CMD cd scripts && ./run_testppddl_laostar.sh ${dir} ${inst} 
