version: '3.3'
services:
  pinedalib_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./files
        target: /files
      - type: bind
        source: ./source
        target: /app
    stdin_open: true
    tty: true
  pinedalib:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./files
        target: /files
    environment:
      - dir=$DIR
      - problem=$INSTANCE
