version: '3.3'
services:
  libmdprddl_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./files
        target: /files
      - type: bind
        source: ./source
        target: /app
    stdin_open: true
    tty: true
  libmdprddl:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./files
        target: /files
    environment:
      - problem=${PROBLEM}
      - solver=$SOLVER
      - heuristic=$HEURISTIC
      - verbosity=$VERBOSITY
      - nsims=$NSIMS
      - interactive=$INTERACTIVE
    stdin_open: true
    tty: true
